/*
 * Copyright 2014 Alessandro Falappa <alex.falappa@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package gui.dialogs;

import ca.odell.glazedlists.BasicEventList;
import ca.odell.glazedlists.FilterList;
import ca.odell.glazedlists.SortedList;
import ca.odell.glazedlists.swing.AdvancedListSelectionModel;
import ca.odell.glazedlists.swing.GlazedListsSwing;
import gui.glazed.MetadataTableFormat;
import gui.glazed.MetadataTableFormatFactory;
import main.data.Metadata;

/**
 * Modeless dialog displaying a tabular view of queryed metadata.
 *
 * @author Alessandro Falappa <alex.falappa@gmail.com>
 */
public class MetadataDialog extends javax.swing.JDialog {

    private BasicEventList<Metadata> dataList;
    private FilterList<Metadata> filterList;
    private SortedList<Metadata> sortedList;
    private AdvancedListSelectionModel<Metadata> selModel;

    public MetadataDialog(java.awt.Frame parent) {
        super(parent, false);
        initComponents();
    }

    public void setDataList(BasicEventList<Metadata> list) {
        dataList = list;
        sortedList = new SortedList<>(dataList);
        final MetadataTableFormat mtf = MetadataTableFormatFactory.createTableFormat(list.get(0));
        tblMetadata.setModel(GlazedListsSwing.eventTableModelWithThreadProxyList(sortedList, mtf));
        selModel = GlazedListsSwing.eventSelectionModel(sortedList);
        //TODO filtering trough a search textfield
        // filterList=new FilterList<>(sortedList, null);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroller = new javax.swing.JScrollPane();
        tblMetadata = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        scroller.setViewportView(tblMetadata);

        getContentPane().add(scroller, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scroller;
    private javax.swing.JTable tblMetadata;
    // End of variables declaration//GEN-END:variables
}
