/*
 * Copyright 2014 Alessandro Falappa <alex.falappa@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package gui.dialogs;

import ca.odell.glazedlists.BasicEventList;
import ca.odell.glazedlists.SortedList;
import ca.odell.glazedlists.swing.AdvancedListSelectionModel;
import ca.odell.glazedlists.swing.AdvancedTableModel;
import ca.odell.glazedlists.swing.GlazedListsSwing;
import gui.glazed.MetadataTableFormat;
import gui.glazed.MetadataTableFormatFactory;
import javax.swing.event.ListSelectionListener;
import main.data.Metadata;
import net.falappa.swing.table.TableColumnAdjuster;

/**
 * Modeless dialog displaying a tabular view of queryed metadata.
 *
 * @author Alessandro Falappa <alex.falappa@gmail.com>
 */
public class MetadataDialog extends javax.swing.JDialog {

    private BasicEventList<Metadata> dataList;
//    private FilterList<Metadata> filterList;
    private SortedList<Metadata> sortedList;
    private AdvancedListSelectionModel<Metadata> selModel;
    private final TableColumnAdjuster adjuster;
    private AdvancedTableModel<Metadata> tblModel;

    public MetadataDialog(java.awt.Frame parent) {
        super(parent, false);
        initComponents();
        adjuster = new TableColumnAdjuster(tblMetadata);
    }

    public void setDataList(BasicEventList<Metadata> list) {
        if (list.isEmpty()) {
            return;
        }
        dataList = list;
        sortedList = new SortedList<>(dataList);
        //TODO filtering trough a search textfield
        // filterList=new FilterList<>(sortedList, null);
        selModel = GlazedListsSwing.eventSelectionModel(sortedList);
        //TODO higlight selected item on map
        tblMetadata.setSelectionModel(selModel);
        final MetadataTableFormat mtf = MetadataTableFormatFactory.createTableFormat(dataList.get(0));
        tblModel = GlazedListsSwing.eventTableModelWithThreadProxyList(sortedList, mtf);
        tblMetadata.setModel(tblModel);
    }

    public void addListSelectionListener(ListSelectionListener x) {
        selModel.addListSelectionListener(x);
    }

    public void removeListSelectionListener(ListSelectionListener x) {
        selModel.removeListSelectionListener(x);
    }

    public void updateFinished() {
        final MetadataTableFormat mtf = MetadataTableFormatFactory.createTableFormat(dataList.get(0));
        tblModel.setTableFormat(mtf);
        adjuster.adjustColumns();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this
     * method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroller = new javax.swing.JScrollPane();
        tblMetadata = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Metadata");
        setPreferredSize(new java.awt.Dimension(800, 200));

        tblMetadata.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblMetadata.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scroller.setViewportView(tblMetadata);

        getContentPane().add(scroller, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scroller;
    private javax.swing.JTable tblMetadata;
    // End of variables declaration//GEN-END:variables
}
